### PR TITLE
Adds Monet.js

### PR DESCRIPTION
**Pull request by naehrstoff**
This is an ok library, but it doesn't support the Fantasy Land spec, so
it isn't really for me (why reinvent the wheel …). However, it is always
an inspiration to look at the source code of different implementations
and learn from them, so this could be added to this list.

This conflict brings up a question I have for other similar libraries:
should there maybe be a section called “Alternative Implementations” or
“Inspiration”? Older/less used libraries could go there.

### CODE REVIEW

**Comment by stoeffel** [comment]
hmm... a section for older less used libs seams not really useful to me. We can add a comment to the description if necessary. But I was thinking to create a subsection for algebraic datastructures (similar to the lens subsection). what do you think?

**Comment by naehrstoff** [comment]
I think more subsections make sense not necessarily to make the list more parseable, but rather to bring attention to groups of topics and how they can be solved with JS. Just knowing that things have names is exteremely helpful to a beginner, I think.

I'm also not sure whether a list of older libs would be useful. Was thinking of it because there are so many that don't really make sense today anymore but were an important step in exploring the topic, e.g. http://blog.osteele.com/posts/2007/07/functional-javascript/ or https://fogus.github.io/lemonad/ – they show different ways of attacking the problem in JS.

I wouldn't really add Monet to the recommended list, but it can very well be useful for some people, so I'm not sure how to handle it. Ahh, it's difficult :D

**Comment by stoeffel** [comment]
> I think more subsections make sense not necessarily to make the list more parseable, but rather to bring attention to groups of topics and how they can be solved with JS. Just knowing that things have names is exteremely helpful to a beginner, I think.

totally agreed.



hmm... I think we just add awesome stuff and make exceptions for useful/educational older/not maintained staff and make a comment in the description.

**Comment by stoeffel** [comment]
something like this:

> [lemonad](https://github.com/fogus/lemonad) - an experiment in elegant JS (***not maintained***)

**Comment by naehrstoff** [comment]
Like the idea, we could maybe also add a year. I'll try with some other libs and add some more PRs later to see how this goes.

**Comment by stoeffel** [comment]
> Like the idea, we could maybe also add a year. I'll try with some other libs and add some more PRs later to see how this goes.

:+1: 

Could you rebase this PR? I will merge it then.

**Comment by naehrstoff** [comment]
Closing because I have integrated the Monet.js link into the Readme in the `reorg` branch.

**Pull request closed without merging**
