### PR TITLE
Adds funko

### PR DESCRIPTION
**Pull request by mickvangelderen**
When I started out with FP I felt lost in the number of available functions in commonly used libraries such as Ramda. Its implementation was difficult to understand because of optimizations and assertions. 

This is why I want to suggest adding funko to the learning resources section. Funko is "An example implementation of basic functional programming concepts. The code is kept as simple as possible so you can learn from code instead of documentation."

### CODE REVIEW

**Comment by stoeffel** [comment]
Hey thanks for your submission. I will check it out.

**Comment by stoeffel** [comment]
Sorry, for the delay.
I think this could become a nice starting point for beginners to learn how fp-libs are built. But I feel it's a little early atm. To be a nice leaning resource, I think it would need more guidance of where to start reading the code and more comments in the code to explain the implementation.
I hope you understand my hesitation to merge this right now.
@naehrstoff what's your opinion?

**Comment by naehrstoff** [comment]
I agree with @stoeffel that more guidance would be needed. I had a difficult time in the beginning to understand what those seemingly thousands of functions in Underscore and Ramda were all about and the documentation was often thin. With Funko you, too, introduce many single-line functions whose purpose is not clear to the beginner. For me less functions with more comments on use-cases and examples would be preferable.

But thanks for your effort, I hope you keep it going!

**Comment by stoeffel** [comment]
So let's close it for know and reopen it when ready.
@mickvangelderen thanks again and let us know when you think it's ready.

**Comment by mickvangelderen** [comment]
Thanks for the constructive feedback with which I absolutely agree.

**Pull request closed without merging**
